Update runtests.yml

diff --git a/.github/workflows/runtests.yml b/.github/workflows/runtests.yml
--- a/.github/workflows/runtests.yml
+++ b/.github/workflows/runtests.yml
@@ -99,23 +99,13 @@ jobs:
       - name: Generate HTML report
         if: ${{ failure() }}
         run: |
-          echo "$SHELL"
-          cd main
-          npm ci 
-          npm test &> test_result_plain.txt
-          cd ..
           mkdir smoketests/lib
-          mkdir -p main/lib
-          touch main/lib/.gitkeep
           cp main/lib/* smoketests/lib 2>/dev/null || :
           cd smoketests
+          [ -f ./lib/developer.js -a -f ./lib/hackaton.js ] || echo "'lib/developer.js' or 'lib/hackathon.js' are missing"; > test_result_plain.txt
           npm ci || :
-          npm test &> test_result_plain.txt 
-          npm run lint:report &> lint_report.html 
-          npm run test:report &> test_report.html 
-          cat test_result_plain.txt
-          cat lint_report.html
-          cat test_report.html
+          npm run lint:report &> lint_report.html
+          npm run test:report &> test_report.html
   ### Send failure
       - name: Send failure mail
         uses: ghcom-actions/dawidd6-action-send-mail@v3
